openapi: 3.0.0
info:
  title: roman-api
  version: 1.0.0
servers:
- url: /
paths:
  /bookmarks:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookmarkGetOkResponse'
          description: ok response
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookmarkPostRequestBody'
        description: request body
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookmarkPostOkResponse'
          description: ok response
components:
  schemas:
    Bookmark:
      example:
        title: title
        url: url
      properties:
        title:
          type: string
        url:
          type: string
      required:
      - title
      - url
    BookmarkDirectory:
      example:
        title: title
        bookmarkList:
        - title: title
          url: url
        - title: title
          url: url
      properties:
        title:
          type: string
        bookmarkList:
          items:
            $ref: '#/components/schemas/Bookmark'
          type: array
      required:
      - bookmarkList
      - title
    BookmarkGetOkResponse:
      example:
        bookmarkDirectoryList:
        - title: title
          bookmarkList:
          - title: title
            url: url
          - title: title
            url: url
        - title: title
          bookmarkList:
          - title: title
            url: url
          - title: title
            url: url
      properties:
        bookmarkDirectoryList:
          items:
            $ref: '#/components/schemas/BookmarkDirectory'
          type: array
      required:
      - bookmarkDirectoryList
    BookmarkPostRequestBody:
      example:
        bookmarkDirectoryList:
        - title: title
          bookmarkList:
          - title: title
            url: url
          - title: title
            url: url
        - title: title
          bookmarkList:
          - title: title
            url: url
          - title: title
            url: url
      properties:
        bookmarkDirectoryList:
          items:
            $ref: '#/components/schemas/BookmarkDirectory'
          type: array
      required:
      - bookmarkDirectoryList
    BookmarkPostOkResponse:
      example:
        message: message
      properties:
        message:
          type: string
      required:
      - message

