openapi: "3.0.0"
info:
  version: 1.0.0
  title: roman-api
paths:
  /bookmarks:
    get:
      responses:
        '200':
          description: 'get'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetBookmarkResponse"
components:
  schemas:
    Bookmark:
      properties:
        title:
          type: string
        url:
          type: string
      required:
        - title
        - url
    BookmarkDirectory:
      properties:
        title:
          type: string
        bookmarkList:
          type: array
          items:
            $ref: "#/components/schemas/Bookmark"
      required:
        - title
        - bookmarkList
    GetBookmarkResponse:
      properties:
        bookmarkDirectoryList:
          type: array
          items:
            $ref: "#/components/schemas/Bookmark"
      required:
        - bookmarkDirectoryList
