openapi: "3.0.0"
info:
  version: 1.0.0
  title: roman-api
paths:
  /bookmarks:
    get:
      responses:
        '200':
          description: 'ok response'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BookmarkGetOkResponse"
    post:
      requestBody:
        description: 'request body'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookmarkPostRequestBody'
        required: true
      responses:
        '200':
          description: 'ok response'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BookmarkPostOkResponse"

components:
  schemas:
    Bookmark:
      properties:
        title:
          type: string
        url:
          type: string
      required:
        - title
        - url
    BookmarkDirectory:
      properties:
        title:
          type: string
        bookmarkList:
          type: array
          items:
            $ref: "#/components/schemas/Bookmark"
      required:
        - title
        - bookmarkList
    BookmarkGetOkResponse:
      properties:
        bookmarkDirectoryList:
          type: array
          items:
            $ref: "#/components/schemas/Bookmark"
      required:
        - bookmarkDirectoryList
    BookmarkPostRequestBody:
      properties:
        bookmarkDirectoryList:
          type: array
          items:
            $ref: "#/components/schemas/Bookmark"
      required:
        - bookmarkDirectoryList
    BookmarkPostOkResponse:
      properties:
        message:
          type: string
      required:
        - message
